#!/bin/bash
#
# Script de déploiement automatique de l'infrastructure GCP pour uBear DW
# Déploie Cloud SQL + Pub/Sub + IAM via Terraform
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "=============================================="
echo "  uBear Data Warehouse - GCP Deployment"
echo "  Architecture: Cloud SQL + Pub/Sub"
echo "=============================================="
echo -e "${NC}"

# =============================================================================
# 1. Vérifications préalables
# =============================================================================

echo -e "${YELLOW}[1/8] Vérification des prérequis...${NC}"

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    echo -e "${RED}❌ gcloud CLI n'est pas installé${NC}"
    echo "Installer: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Check if terraform is installed
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform n'est pas installé${NC}"
    echo "Installer: https://www.terraform.io/downloads"
    exit 1
fi

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}⚠️  jq n'est pas installé (optionnel mais recommandé)${NC}"
    echo "Installer: sudo apt install jq"
fi

echo -e "${GREEN}✅ Tous les prérequis sont installés${NC}"

# =============================================================================
# 2. Configuration GCP
# =============================================================================

echo -e "\n${YELLOW}[2/8] Configuration GCP...${NC}"

# Get current project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null)

if [ -z "$CURRENT_PROJECT" ]; then
    echo -e "${RED}❌ Aucun projet GCP configuré${NC}"
    echo "Exécuter: gcloud config set project YOUR_PROJECT_ID"
    exit 1
fi

echo -e "${GREEN}✅ Projet GCP: ${CURRENT_PROJECT}${NC}"

# Ask for confirmation
read -p "Utiliser ce projet pour le déploiement? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Déploiement annulé"
    exit 0
fi

# =============================================================================
# 3. Enable required APIs
# =============================================================================

echo -e "\n${YELLOW}[3/8] Activation des APIs GCP...${NC}"

REQUIRED_APIS=(
    "sqladmin.googleapis.com"
    "pubsub.googleapis.com"
    "iam.googleapis.com"
    "cloudresourcemanager.googleapis.com"
    "compute.googleapis.com"
)

for api in "${REQUIRED_APIS[@]}"; do
    echo "   Activation de $api..."
    gcloud services enable "$api" --project="$CURRENT_PROJECT" --quiet
done

echo -e "${GREEN}✅ APIs activées${NC}"

# =============================================================================
# 4. Create terraform.tfvars
# =============================================================================

echo -e "\n${YELLOW}[4/8] Configuration Terraform...${NC}"

cd gcp_infrastructure

if [ ! -f terraform.tfvars ]; then
    echo "Création de terraform.tfvars..."
    
    # Generate secure password
    DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
    
    cat > terraform.tfvars <<EOF
# Generated by deploy_gcp.sh on $(date)
project_id  = "$CURRENT_PROJECT"
region      = "us-central1"
zone        = "us-central1-a"
environment = "dev"

db_user     = "foodapp"
db_password = "$DB_PASSWORD"
db_name     = "foodapp"
EOF

    echo -e "${GREEN}✅ terraform.tfvars créé${NC}"
    echo -e "${YELLOW}⚠️  Mot de passe DB généré: ${DB_PASSWORD}${NC}"
    echo "   Sauvegardez ce mot de passe !"
else
    echo -e "${GREEN}✅ terraform.tfvars existe déjà${NC}"
fi

# =============================================================================
# 5. Terraform Init
# =============================================================================

echo -e "\n${YELLOW}[5/8] Initialisation Terraform...${NC}"

terraform init

echo -e "${GREEN}✅ Terraform initialisé${NC}"

# =============================================================================
# 6. Terraform Plan
# =============================================================================

echo -e "\n${YELLOW}[6/8] Planification de l'infrastructure...${NC}"

terraform plan -out=tfplan

echo -e "${GREEN}✅ Plan Terraform généré${NC}"

# =============================================================================
# 7. Terraform Apply
# =============================================================================

echo -e "\n${YELLOW}[7/8] Déploiement de l'infrastructure...${NC}"
echo "Cela va créer:"
echo "  • Cloud SQL PostgreSQL (db-f1-micro)"
echo "  • 5 Pub/Sub topics (eater, merchant, courier, trip_events, schema)"
echo "  • 4 Pub/Sub subscriptions"
echo "  • 2 Service Accounts (Debezium + Databricks)"
echo "  • IAM roles et permissions"
echo ""
read -p "Confirmer le déploiement? (y/n) " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Déploiement annulé"
    rm -f tfplan
    exit 0
fi

terraform apply tfplan

rm -f tfplan

echo -e "${GREEN}✅ Infrastructure déployée${NC}"

# =============================================================================
# 8. Initialize Cloud SQL Database
# =============================================================================

echo -e "\n${YELLOW}[8/8] Initialisation de la base de données...${NC}"

# Get Cloud SQL connection info
CLOUD_SQL_IP=$(terraform output -raw cloud_sql_public_ip)
CLOUD_SQL_CONN_NAME=$(terraform output -raw cloud_sql_connection_name)
DB_PASSWORD=$(grep db_password terraform.tfvars | cut -d'"' -f2)

echo "IP Cloud SQL: $CLOUD_SQL_IP"

# Wait for Cloud SQL to be ready
echo "Attente que Cloud SQL soit prêt (30 secondes)..."
sleep 30

# Upload init script to Cloud SQL
echo "Exécution du script d'initialisation..."
gcloud sql connect ${CLOUD_SQL_CONN_NAME%%:*} \
    --user=foodapp \
    --database=foodapp \
    --quiet < init_cloud_sql.sql

echo -e "${GREEN}✅ Base de données initialisée${NC}"

# =============================================================================
# Summary
# =============================================================================

echo -e "\n${GREEN}"
echo "=============================================="
echo "  Déploiement terminé avec succès ! 🎉"
echo "=============================================="
echo -e "${NC}"

echo -e "${BLUE}Informations de connexion:${NC}"
echo "  Cloud SQL IP: $CLOUD_SQL_IP"
echo "  Database: foodapp"
echo "  User: foodapp"
echo "  Password: $DB_PASSWORD"
echo ""

echo -e "${BLUE}Pub/Sub Topics créés:${NC}"
terraform output -json pubsub_topics | jq -r 'to_entries[] | "  • \(.key): \(.value)"'
echo ""

echo -e "${BLUE}Service Accounts:${NC}"
echo "  • Debezium: $(terraform output -raw debezium_service_account)"
echo "  • Databricks: $(terraform output -raw databricks_service_account)"
echo ""

echo -e "${YELLOW}Prochaines étapes:${NC}"
echo "  1. Télécharger les clés de service account:"
echo "     gcloud iam service-accounts keys create debezium-sa-key.json \\"
echo "       --iam-account=$(terraform output -raw debezium_service_account)"
echo ""
echo "     gcloud iam service-accounts keys create databricks-sa-key.json \\"
echo "       --iam-account=$(terraform output -raw databricks_service_account)"
echo ""
echo "  2. Mettre à jour .env avec les nouvelles valeurs"
echo "  3. Déployer Debezium (voir README_GCP.md)"
echo "  4. Configurer Databricks (voir README_GCP.md)"
echo ""

# Save summary to file
cat > deployment_summary.txt <<EOF
uBear Data Warehouse - GCP Deployment Summary
==============================================
Deployment Date: $(date)
GCP Project: $CURRENT_PROJECT

Cloud SQL:
  IP: $CLOUD_SQL_IP
  Connection Name: $CLOUD_SQL_CONN_NAME
  Database: foodapp
  User: foodapp
  Password: $DB_PASSWORD

Pub/Sub Topics:
$(terraform output -json pubsub_topics | jq -r 'to_entries[] | "  \(.key): \(.value)"')

Service Accounts:
  Debezium: $(terraform output -raw debezium_service_account)
  Databricks: $(terraform output -raw databricks_service_account)

Next Steps:
  1. Download service account keys
  2. Update .env file
  3. Deploy Debezium connector
  4. Configure Databricks pipelines
EOF

echo -e "${GREEN}✅ Résumé sauvegardé dans deployment_summary.txt${NC}"

cd ..
