FROM python:3.10-slim

# Installe Java (nécessaire pour Spark)
RUN apt-get update && apt-get install -y openjdk-11-jre-headless && rm -rf /var/lib/apt/lists/*

# Installe pyspark
RUN pip install pyspark==3.5.0 pandas

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin

WORKDIR /opt/spark-apps